apiVersion: v1
kind: Template
metadata:
  name: spice-remoting-apps
objects:

- apiVersion: v1
  kind: Service
  metadata:
    name: spice-proxy
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spice-app
      deploymentconfig: spice-app
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: spice-app
    name: spice-app
  spec:
    replicas: 1
    selector:
      app: spice-app
      deploymentconfig: spice-app
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: spice-app
          deploymentconfig: spice-app
      spec:
        containers:
        - image: ' '
          imagePullPolicy: Always
          name: vscode
          ports:
          - containerPort: 8080
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vscode
        from:
          kind: ImageStreamTag
          name: vscode:latest
      type: ImageChange

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: spice-base
    name: spice-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: spice-base:latest
    runPolicy: Serial
    source:
      contextDir: spice
      git:
        uri: https://github.com/jcpowermac/openshift-spice
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: fedora:27
      type: Docker
    triggers:
    - imageChange:
      type: ImageChange

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: vscode
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: vscode:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/jcpowermac/openshift-spice
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: spice/Dockerfile.vscode
        from:
          kind: ImageStreamTag
          name: spice-base:latest
      type: Docker
    triggers:
    - imageChange:
      type: ImageChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fedora
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/fedora:27
      name: "27"

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: spice-base

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: vscode

- apiVersion: v1
  kind: Route
  metadata:
    name: spice
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: spice-proxy
      weight: 100
    wildcardPolicy: None
